### ISSUE TITLE
Error 500 at Import PIM Data

### ISSUE THREAD

**Issue by gammyduck** [Agence-DnD/PIMGento#233]
Installed on Magento 1.9.7 and can change settings in configuration but not access the Import PIM Data.

[Thu Apr 26 20:08:43.360330 2018] [access_compat:error] [pid 30483] [client 127.0.0.1:51213] AH01797: client denied by server configuration: /xxxx/public_html/app/etc/local.xml
[Thu Apr 26 20:09:02.561107 2018] [proxy_fcgi:error] [pid 30622] [client 127.0.0.1:51238] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getParams() on null in /xxx/public_html/app/code/community/Pimgento/Core/Block/Adminhtml/Launcher.php:20\nStack trace:\n#0 /xxx/public_html/app/code/core/Mage/Core/Model/Layout.php(491): Pimgento_Core_Block_Adminhtml_Launcher->__construct(Array)\n#1 /xxx/public_html/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('Pimgento_Core_B...', Array)\n#2 /xxx/public_html/app/code/community/Pimgento/Core/Block/Adminhtml/Task.php(18): Mage_Core_Model_Layout->createBlock('pimgento_core/a...')\n#3 /xxx/public_html/app/code/core/Mage/Core/Block/Abstract.php(297): Pimgento_Core_Block_Adminhtml_Task->_prepareLayout()\n#4 /xxx/public_html/app/code/core/Mage/Core/Model/...\nPHP message: PHP Stack trace:\nPHP message: PHP   1. newrelic_exception_handler() UNKNOWN?:0\n', referer: http://xxx.com/index.php/admin/process/list/key/14f6020541f65ddd92d098a0e285c10a/

**Comment by DnD-Hellion** [comment]
Hi @gammyduck ,
Thank you for using PIMGento.

It seems your bug comes from app/code/community/Pimgento/Core/Block/Adminhtml/Launcher.php:20, $this->getConfig() seems to be empty.

Could you please debug this and come back to us ?

Looking forward to reading you.
Best regards,

**Comment by Dnd-Gimix** [comment]
Hi @gammyduck,

Any news on this issue ?

Regards

**Comment by baljinderimpinge** [comment]
@DnD-Hellion 

Hello I am also facing similar issue can you or @Dnd-Gimix help me out in this?

Waiting to hear back from you.

Thanks

**Comment by Dnd-Gimix** [comment]
Hello @baljinderimpinge ,

Thank you for your interest in PIMGento.

Unfortunately, as this repository is not maintained anymore, we are not providing any support on it.
This might be related to the block dependency : Mage_Adminhtml_Block_Media_Uploader

Thank you for your understanding.

Regards,
